development:
  adapter: postgresql
  encoding: unicode
  database: damon_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: damon_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: damon_production
  username: rails
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
