source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1'
# Use sqlite3 as the database for Active Record
gem "pg"
# Use Puma as the app server
# gem 'puma', '~> 3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', :require => 'rack/cors'
gem 'aws-sdk', '~> 2'
gem 'active_model_serializers', '~> 0'
gem 'rollbar'
gem 'google-id-token'

gem 'haml-rails'
gem 'bourbon'
gem 'sass-rails'
gem 'uglifier'

gem 'sprockets-commonjs', github: "maccman/sprockets-commonjs", ref: "8137f91"
gem 'react-rails'
source 'https://rails-assets.org' do
  gem 'rails-assets-es5-shim', '~> 4.1.3'
  gem 'rails-assets-es6-shim', '~> 0.35.0'
  gem 'rails-assets-fetch', '0.11.0' # polyfill for html5 fetch()
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem "pry"
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'better_errors'
  gem 'capistrano', '>= 3.3.5'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler' # for capistrano/bundler
  gem 'capistrano-rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
